---
title: "Introduction"
author: "Ambre Dormal"
date: "18/04/2020"
categories:
  - "Introduction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I have decided to dedicate my blog to "Ocean health", a theme which is very close to my heart. Various topics will be covered in this portfolio such as plastic pollution, ocean acidification and the impact of human activities on marine life.

One of the problems that often comes up when we talk about ocean health is plastic pollution.

According to "Le Figaro", 10 tons of plastic are produced worldwide per second and many of them will only be used once. Only 9% of all this plastic will be recycled.

The management of plastic waste is still insufficient. According to “The SeaCleaners”, every year 80,000,000 tons of plastic waste reach seas and oceans where they can have a long life according to the fact that they are not biodegradable.
This is a real danger for our oceans and for marine fauna and flora.

Still according to « The SeaCleaners”, 75% of all marine litter sink on the ocean floor. They are thus no longer recyclable and degrade extremely slowly. The remaining 25% drift and are being carried away by ocean currents. They end up on beaches or end up fragmenting into smaller and smaller pieces until becoming plastic nanoparticles which are then impossible to recyclable since they are invisible for us.

The big danger of nanoplastics is that they can be easily ingested by marine organisms and end up in their tissues and digestive tract. The study of nanoplastics is still too recent for us to know their consequences on marine life but everything suggests that they have a negative impact on the good development of marine animals.

Macroplastics are just as dangerous since they are traps for marine life. Like for example the plastic bottles where the Hermit Crabs get stuck and find death, turtles that get stuck in plastic bags they can’t get rid of, seabirds that unintentionally ingest plastic, ...

Another major problem, less known perhaps, is the acidification of oceans. This acidification results from a decrease in pH. This is mainly due to a higher absorption of CO2 by oceans due to an increase in C02 concentration in our atmosphere because of human’s activities.
The problem is that many marine species are sensitive to pH change, and therefore can only live in a very short pH range. The first affected are corals and organisms containing a calcareous shell or skeleton such as Dungeness crab, for example.

It essential now to find solutions about all these problems before they become bigger otherwise life in the oceans will probably no longer resemble to the one we know.

