---
title: "My English Activity Log"
author:
name: "Ambre Dormal"
date: 10-09-2019
categories:
  - "My English Activity Log"
preview: 
output:
  distill::distill_article:
    self_contained: false
---

# Movie and tv shows : 
**10/15/2019** : I watched the last Harry Potter in VO

**11/03/2019** : I started watchinch season 3 of Atypical in v.o. with subtitles

**11/14/2019** : I continue to watch season 3 of Atypical in video with subtiles, it's easier to understand that I thought, I'm now  at the episode five 

**02/03/2020** : I watched some episodes of Friends in V.O. I don't understand everything so I use the subtitles in V.O.

**02/23/2020** : I watch the whole serie "The act" in V.O. (so in English) whereas I put the subtitles in English because the actors speak too fast but despite that it was quite clear. This serie tells the facts of a true story which is very interesting.  It is the story of a mother who made the world believe that her daughter was seriously ill to receive money. She somehow held her daughter hostage who one day discovered her mother's terrible lies and ended up killing her to free herself from her ordeal.

# Youtube videos :
**10/18/2019** : I watched a video about grey parrots

**10/21/2019** : I watched some video on the channel "Jubilee"

**11/10/2019** : I watched some videos very interesting on the channel "What if". The video " What If You Were Swallowed by a Whale?" was in fact very frightening, I also watch "What If the Ocean Was Transparent?" and "What If We Lost The Amazon Rainforest?". I like these video because they speek clearly and I understand everything they say or almost all.

**01/15/2020** : I watched scientifics videos in English about Nikola Tesla and the real story of Bloody Mary. The last one was quite complicated to understand so I use the subtitles in V.O. to better understand.

**02/23/2020** : I watched some videos in English on the channel " TED-Ed". The vocabulaire use in theses videos was quite easy to understand and I didn't have to put the subtitles . Here is the name of the videos : "Rosalind Franklin: DNA's unsung hero." & "The genius of Marie Curie". The videos are not too long not too short so this is perfect , I subscribed to this channel.

**02/26/2020** : I kept watching videos on the channel "TED-Ed": "What would happen if every human suddenly disappeared?", "Where do superstitions come from?", "How does cafeine keep us awake?", "What causes insomnia?" and "Hacking bacteria to fight cancer" who was harder to understand than the other videos. This kind of video is nice because they only lasts five minutes so you don't get bored.

**03/29/2020** : I watched a series of dissection videos in English for my "Biologie Animale" course , this was easy to understand.

# Reading : 
**10/21/2019** : I read some news about Amazon Rainforest

**10/30/2019** : I did some research for my presentation + find and read the article 2 for my blog

**11/02/2019** : I read other facts about the Amazon rainforest

**11/13/2019** : I read an interesting article about plastic find in stomachs' fishes, I decided to choose this one as article 3 so I analysed it and put it on my blog

**11/17/2019** : My mother bought me a National Geographic's magazine in english about, a subject that I particularly like, "Mars, secrets of the Red Planet". I read the first ten pages, the voc is sometimes difficult but I use the app "WordReference" if I really can't understand the sentence.

**11/24/2019**  :I read the news on the BBC app

**11/28/2019** : I read the news about Ocean, Whales and Pollution on different site especially Global Citizen

**03/31/2019** : I read some news about satellite launches because I saw in the sky at 9 p.m. twenty light points that followed each other at the same speed and on the same trajectory, this was very strange, I thought that it was a satellite launch but I didn't see any articles on Google talking about any satellite launch so the mystery remains !

# Others

**09/08/2019** to **09/11/2019** : I have gone in London for four days with my sister and her friend, it was sooo cool. London is a beautiful and rich city in term of culture and architecture. But London is also the perfect place for a potterhead like me ! We went at the Kingcross station more precisely at the 9 3/4 platform shop. The last day we spent the day in Green Park, the squirrels were so cute there, one of them took a nutty in my hands, it was a very exciting moment !

**10/24/2019** : I trained myself to write the lyrics' songs on the app "LyricsTraining"

**10/24/2019** : Use the app "LyricsTraining"

**10/31/2019** : Finish the analysis of the article 2 for my blog

**11/01/2019** : I continue to use "Lyricstraining" 

**11/15/2019** : I've changed the language on my phone, it's now in English

